source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'heroku'

# Bundle gems needed for Mongoid
gem "mongoid", "2.0.0.beta.20"
gem "bson_ext", "1.1.2"

group :development do
  gem "rspec", ">=2.0.0"
  gem "rspec-rails", ">=2.0.0"
  gem "ruby-debug"
end

group :test do
  gem 'factory_girl_rails'
end